package main

import "time"

type SearchBody struct {
	MicrositeType int `json:"MicrositeType"`
	Microsite     struct {
		SiteID                          int         `json:"SiteId"`
		MicrositeType                   int         `json:"MicrositeType"`
		Culture                         string      `json:"Culture"`
		LandingURLSegment               string      `json:"LandingUrlSegment"`
		Keyword                         interface{} `json:"Keyword"`
		SearchResultsURLSegment         string      `json:"SearchResultsUrlSegment"`
		ResearchURLSegment              interface{} `json:"ResearchUrlSegment"`
		ResearchDisplayText             interface{} `json:"ResearchDisplayText"`
		DisplayText                     string      `json:"DisplayText"`
		ShortName                       string      `json:"ShortName"`
		MediumName                      interface{} `json:"MediumName"`
		ShortNameGender                 string      `json:"ShortNameGender"`
		RequiresType                    bool        `json:"RequiresType"`
		RequiresSubType                 bool        `json:"RequiresSubType"`
		Category2Ids                    []int       `json:"Category2Ids"`
		DisableSeoModel                 bool        `json:"DisableSeoModel"`
		DefaultWithPrice                bool        `json:"DefaultWithPrice"`
		DefaultWithPhotos               bool        `json:"DefaultWithPhotos"`
		IsNpv                           bool        `json:"IsNpv"`
		DisplayNeuvesInNpvPopularLinks  bool        `json:"DisplayNeuvesInNpvPopularLinks"`
		NextPrevSearchCriteriaOverrides interface{} `json:"NextPrevSearchCriteriaOverrides"`
	} `json:"Microsite"`
	Address                        string      `json:"Address"`
	Proximity                      int         `json:"Proximity"`
	WithFreeCarProof               bool        `json:"WithFreeCarProof"`
	WithPrice                      bool        `json:"WithPrice"`
	WithPhotos                     bool        `json:"WithPhotos"`
	HasLiveChat                    bool        `json:"HasLiveChat"`
	HasVirtualAppraisal            bool        `json:"HasVirtualAppraisal"`
	HasHomeTestDrive               bool        `json:"HasHomeTestDrive"`
	HasOnlineReservation           bool        `json:"HasOnlineReservation"`
	HasDigitalRetail               bool        `json:"HasDigitalRetail"`
	HasDealerDelivery              bool        `json:"HasDealerDelivery"`
	HasTryBeforeYouBuy             bool        `json:"HasTryBeforeYouBuy"`
	HasMoneyBackGuarantee          bool        `json:"HasMoneyBackGuarantee"`
	IsNew                          bool        `json:"IsNew"`
	IsUsed                         bool        `json:"IsUsed"`
	IsDamaged                      bool        `json:"IsDamaged"`
	IsCpo                          bool        `json:"IsCpo"`
	IsDealer                       bool        `json:"IsDealer"`
	IsPrivate                      bool        `json:"IsPrivate"`
	Top                            string      `json:"Top"`
	Make                           interface{} `json:"Make"`
	Model                          interface{} `json:"Model"`
	BodyType                       interface{} `json:"BodyType"`
	PriceAnalysis                  interface{} `json:"PriceAnalysis"`
	PhoneNumber                    string      `json:"PhoneNumber"`
	PriceMin                       interface{} `json:"PriceMin"`
	PriceMax                       interface{} `json:"PriceMax"`
	WheelBaseMin                   interface{} `json:"WheelBaseMin"`
	WheelBaseMax                   interface{} `json:"WheelBaseMax"`
	EngineSizeMin                  interface{} `json:"EngineSizeMin"`
	EngineSizeMax                  interface{} `json:"EngineSizeMax"`
	LengthMin                      interface{} `json:"LengthMin"`
	LengthMax                      interface{} `json:"LengthMax"`
	WeightMin                      interface{} `json:"WeightMin"`
	WeightMax                      interface{} `json:"WeightMax"`
	HorsepowerMin                  interface{} `json:"HorsepowerMin"`
	HorsepowerMax                  interface{} `json:"HorsepowerMax"`
	HoursMin                       interface{} `json:"HoursMin"`
	HoursMax                       interface{} `json:"HoursMax"`
	OdometerMin                    interface{} `json:"OdometerMin"`
	OdometerMax                    interface{} `json:"OdometerMax"`
	YearMin                        interface{} `json:"YearMin"`
	YearMax                        interface{} `json:"YearMax"`
	Keywords                       string      `json:"Keywords"`
	FuelTypes                      interface{} `json:"FuelTypes"`
	Transmissions                  interface{} `json:"Transmissions"`
	Colours                        interface{} `json:"Colours"`
	Drivetrain                     interface{} `json:"Drivetrain"`
	Engine                         interface{} `json:"Engine"`
	SeatingCapacity                interface{} `json:"SeatingCapacity"`
	NumberOfDoors                  interface{} `json:"NumberOfDoors"`
	Sleeps                         interface{} `json:"Sleeps"`
	SlideOuts                      interface{} `json:"SlideOuts"`
	Trim                           interface{} `json:"Trim"`
	RelatedCompanyOwnerCompositeID interface{} `json:"RelatedCompanyOwnerCompositeId"`
	SrpNewCarWidgetVariant         interface{} `json:"SrpNewCarWidgetVariant"`
	IsUniqueSearch                 bool        `json:"IsUniqueSearch"`
	InMarketType                   string      `json:"InMarketType"`
	Skip                           int         `json:"Skip"`
	SortBy                         string      `json:"SortBy"`
}

type SearchResponse struct {
	PreviousListingsCount      int    `json:"PreviousListingsCount"`
	AdSenseHTML                string `json:"AdSenseHtml"`
	AdsHTML                    string `json:"AdsHtml"`
	AlternativeLanguageURI     string `json:"AlternativeLanguageUri"`
	BreadcrumbsHTML            string `json:"BreadcrumbsHtml"`
	Count                      int    `json:"Count"`
	DeepLinkHTML               string `json:"DeepLinkHtml"`
	GoogleTagManagerKey        string `json:"GoogleTagManagerKey"`
	GtmDataLayerScript         string `json:"GtmDataLayerScript"`
	GtmRemarketingParamsScript string `json:"GtmRemarketingParamsScript"`
	Header                     string `json:"Header"`
	LocationJSON               string `json:"LocationJson"`
	Proximity                  int    `json:"Proximity"`
	SearchCriteria             struct {
		Address            string        `json:"Address"`
		AdStatus           []int         `json:"AdStatus"`
		AdType             []int         `json:"AdType"`
		BodyTypes          []interface{} `json:"BodyTypes"`
		Colours            []interface{} `json:"Colours"`
		CpoStatus          int           `json:"CpoStatus"`
		DatalayerCpoStatus bool          `json:"DatalayerCpoStatus"`
		FuelTypes          []interface{} `json:"FuelTypes"`
		IsCommercial       bool          `json:"IsCommercial"`
		IsUniqueSearch     bool          `json:"IsUniqueSearch"`
		Location           struct {
			City struct {
				PlaceName   string `json:"PlaceName"`
				Coordinates struct {
					Latitude  float64 `json:"Latitude"`
					Longitude float64 `json:"Longitude"`
				} `json:"Coordinates"`
				Name     string `json:"Name"`
				Province struct {
					Abbreviation string `json:"Abbreviation"`
					Name         string `json:"Name"`
				} `json:"Province"`
				PostalCode string `json:"PostalCode"`
				IsCity     bool   `json:"IsCity"`
			} `json:"City"`
			Confidence float64 `json:"Confidence"`
		} `json:"Location"`
		MicrositeType      int           `json:"MicrositeType"`
		Trims              []interface{} `json:"Trims"`
		PageNumber         int           `json:"PageNumber"`
		Proximity          int           `json:"Proximity"`
		Skip               int           `json:"Skip"`
		Sleeps             []interface{} `json:"Sleeps"`
		SlideOut           []interface{} `json:"SlideOut"`
		Top                int           `json:"Top"`
		Transmissions      []interface{} `json:"Transmissions"`
		WithPhotos         bool          `json:"WithPhotos"`
		WithPrice          bool          `json:"WithPrice"`
		HasNewAdStatus     bool          `json:"HasNewAdStatus"`
		HasUsedAdStatus    bool          `json:"HasUsedAdStatus"`
		HasDamagedAdStatus bool          `json:"HasDamagedAdStatus"`
		HasAdTypeDealer    bool          `json:"HasAdTypeDealer"`
		HasAdTypePrivate   bool          `json:"HasAdTypePrivate"`
		SortBy             int           `json:"SortBy"`
		InMarketType       string        `json:"InMarketType"`
		Microsite          struct {
			SiteID                         int    `json:"SiteId"`
			MicrositeType                  int    `json:"MicrositeType"`
			Culture                        string `json:"Culture"`
			LandingURLSegment              string `json:"LandingUrlSegment"`
			SearchResultsURLSegment        string `json:"SearchResultsUrlSegment"`
			DisplayText                    string `json:"DisplayText"`
			ShortName                      string `json:"ShortName"`
			ShortNameGender                string `json:"ShortNameGender"`
			RequiresType                   bool   `json:"RequiresType"`
			RequiresSubType                bool   `json:"RequiresSubType"`
			Category2Ids                   []int  `json:"Category2Ids"`
			DisableSeoModel                bool   `json:"DisableSeoModel"`
			DefaultWithPrice               bool   `json:"DefaultWithPrice"`
			DefaultWithPhotos              bool   `json:"DefaultWithPhotos"`
			IsNpv                          bool   `json:"IsNpv"`
			DisplayNeuvesInNpvPopularLinks bool   `json:"DisplayNeuvesInNpvPopularLinks"`
		} `json:"Microsite"`
		Drivetrain         []interface{} `json:"Drivetrain"`
		Engine             []interface{} `json:"Engine"`
		SeatingCapacity    []interface{} `json:"SeatingCapacity"`
		NumberOfDoors      []interface{} `json:"NumberOfDoors"`
		IsDefaultAddress   bool          `json:"IsDefaultAddress"`
		CashDown           float64       `json:"CashDown"`
		TradeIn            float64       `json:"TradeIn"`
		PriceAnalysis      []interface{} `json:"PriceAnalysis"`
		SearchCriteriaType int           `json:"SearchCriteriaType"`
		ShowQaAd           bool          `json:"ShowQaAd"`
		IsOnlineSellerPlus bool          `json:"IsOnlineSellerPlus"`
	} `json:"SearchCriteria"`
	SearchCriteriaJSON           string `json:"SearchCriteriaJson"`
	SearchResultsDataJSON        string `json:"SearchResultsDataJson"`
	Title                        string `json:"Title"`
	URL                          string `json:"Url"`
	AdvancedSearchURL            string `json:"AdvancedSearchUrl"`
	DisplayCompareCpo            bool   `json:"DisplayCompareCpo"`
	DatalayerInMarketTypeListKey string `json:"DatalayerInMarketTypeListKey"`
	IsSearchExpanded             bool   `json:"IsSearchExpanded"`
	NumOfAdsOnPage               int    `json:"NumOfAdsOnPage"`
	EnablePaymentTagWithRate     bool   `json:"EnablePaymentTagWithRate"`
	SavedSearchData              struct {
		SavedSearch struct {
			ID       string `json:"Id"`
			Query    string `json:"Query"`
			Title    string `json:"Title"`
			IsMre    bool   `json:"IsMre"`
			Type     int    `json:"Type"`
			SourceID int    `json:"SourceId"`
		} `json:"SavedSearch"`
		SavedSearchCriteria struct {
			MicrositeType    int    `json:"MicrositeType"`
			MicrositeCulture string `json:"MicrositeCulture"`
			Location         struct {
				Latitude  float64 `json:"Latitude"`
				Longitude float64 `json:"Longitude"`
			} `json:"Location"`
			ProvinceAbbreviation string        `json:"ProvinceAbbreviation"`
			City                 string        `json:"City"`
			Proximity            int           `json:"Proximity"`
			AdStatus             []int         `json:"AdStatus"`
			AdType               []int         `json:"AdType"`
			Trims                []interface{} `json:"Trims"`
			CpoStatus            int           `json:"CpoStatus"`
			BodyTypes            []interface{} `json:"BodyTypes"`
			Colours              []interface{} `json:"Colours"`
			FuelTypes            []interface{} `json:"FuelTypes"`
			Sleeps               []interface{} `json:"Sleeps"`
			SlideOut             []interface{} `json:"SlideOut"`
			SortBy               int           `json:"SortBy"`
			Transmissions        []interface{} `json:"Transmissions"`
			Drivetrain           []interface{} `json:"Drivetrain"`
			Engine               []interface{} `json:"Engine"`
			SeatingCapacity      []interface{} `json:"SeatingCapacity"`
			NumberOfDoors        []interface{} `json:"NumberOfDoors"`
			PriceAnalysis        []interface{} `json:"PriceAnalysis"`
			WithPhotos           bool          `json:"WithPhotos"`
			WithPrice            bool          `json:"WithPrice"`
			CashDown             float64       `json:"CashDown"`
			TradeIn              float64       `json:"TradeIn"`
			Skip                 int           `json:"Skip"`
			Top                  int           `json:"Top"`
			SearchCriteriaType   int           `json:"SearchCriteriaType"`
			ShowQaAd             bool          `json:"ShowQaAd"`
		} `json:"SavedSearchCriteria"`
	} `json:"SavedSearchData"`
	OptimizelyShowSectionHeader bool `json:"OptimizelyShowSectionHeader"`
	SrpNewCarWidgetVariant      int  `json:"SrpNewCarWidgetVariant"`
	ShowSrpNewCarWidget         bool `json:"ShowSrpNewCarWidget"`
	LazyDataCommandArgument     struct {
		RegisteredCallbacks []interface{} `json:"RegisteredCallbacks"`
	} `json:"LazyDataCommandArgument"`
	MostPopularModels []struct {
		BodyType    string   `json:"BodyType"`
		BodyTypeURI []string `json:"BodyTypeUri"`
		Active      bool     `json:"Active"`
		Province    string   `json:"Province"`
		City        string   `json:"City"`
		Model       string   `json:"Model"`
		Link        string   `json:"Link"`
	} `json:"MostPopularModels"`
	NewCarWidgetPosition int    `json:"NewCarWidgetPosition"`
	SrpLocation          string `json:"SrpLocation"`
}

type DatabaseDocument struct {
	Build                   string `json:"build"`
	ClientID                string `json:"clientId"`
	ClientIP                string `json:"clientIp"`
	ClientType              string `json:"clientType"`
	GoogleRemarketingParams struct {
		City      string `json:"city"`
		Condition string `json:"condition"`
		Make      string `json:"make"`
		Model     string `json:"model"`
		Pagetype  string `json:"pagetype"`
		Source    string `json:"source"`
	} `json:"googleRemarketingParams"`
	Lists []struct {
		Key      string `json:"key"`
		Vehicles []struct {
			ActiveUpsells            string `json:"activeUpsells"`
			AdID                     string `json:"adID"`
			AdType                   string `json:"adType"`
			Car360Enabled            string `json:"car360Enabled"`
			Carfax                   string `json:"carfax"`
			Category                 string `json:"category"`
			ChatEnabled              string `json:"chatEnabled"`
			ChatProvider             string `json:"chatProvider"`
			CmPictures               string `json:"cmPictures"`
			Condition                string `json:"condition"`
			DealerID                 string `json:"dealerID"`
			DigitalRetail            string `json:"digitalRetail"`
			FinancingPrice           string `json:"financingPrice"`
			Latlong                  string `json:"latlong"`
			ListingPosition          string `json:"listingPosition"`
			MainPictureCM            string `json:"mainPictureCM"`
			Make                     string `json:"make"`
			MediaTypes               string `json:"mediaTypes"`
			Model                    string `json:"model"`
			Ncse                     string `json:"ncse"`
			Olympus                  string `json:"olympus"`
			PrequalificationLeadForm string `json:"prequalificationLeadForm"`
			Price                    string `json:"price"`
			PriceAnalysis            string `json:"priceAnalysis"`
			PriceHistory             string `json:"priceHistory"`
			Province                 string `json:"province"`
			RawLocation              string `json:"rawLocation"`
			ServiceBadges            string `json:"serviceBadges"`
			ShowInsuranceWidgetOnTop string `json:"showInsuranceWidgetOnTop"`
			Strikethrough            string `json:"strikethrough"`
			SubprimeLeadForm         string `json:"subprimeLeadForm"`
			TestingDimension         string `json:"testingDimension"`
			TotalPictures            string `json:"totalPictures"`
			Transparency             string `json:"transparency"`
			UpgradeBoost             string `json:"upgradeBoost"`
			UpgradeHL                string `json:"upgradeHL"`
			UpgradeInline            string `json:"upgradeInline"`
			UpgradeMobileBoost       string `json:"upgradeMobileBoost"`
			UpgradePL                string `json:"upgradePL"`
			UpgradePPL               string `json:"upgradePPL"`
			UpgradeSwipePro          string `json:"upgradeSwipePro"`
			UpgradeTA                string `json:"upgradeTA"`
			UpgradeTopSpot           string `json:"upgradeTopSpot"`
			UpgradeXPL               string `json:"upgradeXPL"`
			VehicleSpecialist        string `json:"vehicleSpecialist"`
			Year                     string `json:"year"`
		} `json:"vehicles"`
	} `json:"lists"`
	LoginStatus string `json:"loginStatus"`
	Optimizely  struct {
		ExpID string `json:"expId"`
		VarID string `json:"varId"`
	} `json:"optimizely"`
	RequestID string `json:"requestId"`
	Search    struct {
		BodyType         string `json:"bodyType"`
		Category         string `json:"category"`
		Cpo              string `json:"cpo"`
		Damaged          string `json:"damaged"`
		Dealer           string `json:"dealer"`
		Distance         string `json:"distance"`
		Doors            string `json:"doors"`
		DriveTrain       string `json:"driveTrain"`
		Engine           string `json:"engine"`
		ExteriorColor    string `json:"exteriorColor"`
		FilterFieldsUsed string `json:"filterFieldsUsed"`
		FuelType         string `json:"fuelType"`
		ListKey          string `json:"listKey"`
		Location         string `json:"location"`
		Make             string `json:"make"`
		MaxKms           string `json:"maxKms"`
		MaxPrice         string `json:"maxPrice"`
		MaxYear          string `json:"maxYear"`
		MinKms           string `json:"minKms"`
		MinPrice         string `json:"minPrice"`
		MinYear          string `json:"minYear"`
		Model            string `json:"model"`
		Ncse             string `json:"ncse"`
		New              string `json:"new"`
		OnlineSellerPlus string `json:"onlineSellerPlus"`
		PageNumber       string `json:"pageNumber"`
		PriceAnalysis    string `json:"priceAnalysis"`
		PrivateSeller    string `json:"privateSeller"`
		RefinedKeywords  string `json:"refinedKeywords"`
		SbpDownp         string `json:"sbpDownp"`
		SbpFrequency     string `json:"sbpFrequency"`
		SbpMax           string `json:"sbpMax"`
		SbpMin           string `json:"sbpMin"`
		SbpTerm          string `json:"sbpTerm"`
		SbpTradein       string `json:"sbpTradein"`
		SearchLocation   string `json:"searchLocation"`
		SearchType       string `json:"searchType"`
		Seats            string `json:"seats"`
		Services         string `json:"services"`
		SortOrder        string `json:"sortOrder"`
		Transmission     string `json:"transmission"`
		Trim             string `json:"trim"`
		Used             string `json:"used"`
		WithFreeCarProof string `json:"withFreeCarProof"`
		WithPhotos       string `json:"withPhotos"`
		WithPrice        string `json:"withPrice"`
	} `json:"search"`
	ShowRemarketing bool   `json:"showRemarketing"`
	UserID          string `json:"userID"`
}

// BARRRIER ---------------------------------------------------------------	------------------------------------------------------------------------- //

type ListingsResponse struct {
	AllListings []Listing `json:"AllListings"`
	ProvincialPriorityListings []Listing `json:"ProvincialPriorityListings"`
	TopSpotListings []Listing `json:"TopSpotListings"`
	PriorityListingsTop []Listing `json:"PriorityListingsTop"`
	FeaturedListings []Listing `json:"FeaturedListings"`
	PriorityListingsBottom []Listing `json:"PriorityListingsBottom"`
	PriorityListings []Listing `json:"PriorityListings"`
	OrganicListings []Listing `json:"OrganicListings"`
	OrganicProvincialPrioriyListings []Listing `json:"OrganicProvincialPrioriyListings"`
}

type Listing struct {
	AdID                         int      `json:"AdId"`
	AnalyticsOrdinalPosition     int      `json:"AnalyticsOrdinalPosition"`
	Car360Link                   string   `json:"Car360Link"`
	CarFaxMode                   int      `json:"CarFaxMode"`
	CompanyForeignID             string   `json:"CompanyForeignId"`
	DealerID                     string   `json:"DealerId"`
	Description                  string   `json:"Description"`
	IsSrpDescriptionShown        bool     `json:"IsSrpDescriptionShown"`
	DetailPageURL                string   `json:"DetailPageUrl"`
	EasyFinanceLink              string   `json:"EasyFinanceLink"`
	EnableHighlightListings      bool     `json:"EnableHighlightListings"`
	ForeignID                    string   `json:"ForeignId"`
	HasCar360                    bool     `json:"HasCar360"`
	HasVideoEdge                 bool     `json:"HasVideoEdge"`
	HasCustomVideo               bool     `json:"HasCustomVideo"`
	HasStitchedVideo             bool     `json:"HasStitchedVideo"`
	HasYouTubeVideo              bool     `json:"HasYouTubeVideo"`
	ImageGalleryURLList          []string `json:"ImageGalleryUrlList"`
	ImageGalleryResourceLocation int      `json:"ImageGalleryResourceLocation"`
	ImageCount                   int      `json:"ImageCount"`
	CarMediaImageCount           int      `json:"CarMediaImageCount"`
	ImageURL                     string   `json:"ImageUrl"`
	IsAmvoq                      bool     `json:"IsAmvoq"`
	IsCpo                        bool     `json:"IsCpo"`
	IsDealer                     bool     `json:"IsDealer"`
	IsFeaturedListing            bool     `json:"IsFeaturedListing"`
	IsGoldSeries                 bool     `json:"IsGoldSeries"`
	IsHighlightListing           bool     `json:"IsHighlightListing"`
	IsHighlightListingMobile     bool     `json:"IsHighlightListingMobile"`
	IsMobileBoost                bool     `json:"IsMobileBoost"`
	IsBoost                      bool     `json:"IsBoost"`
	IsNewVehicle                 bool     `json:"IsNewVehicle"`
	IsOrganicListings            bool     `json:"IsOrganicListings"`
	IsPassenger                  bool     `json:"IsPassenger"`
	IsPriorityListing            bool     `json:"IsPriorityListing"`
	IsPrivate                    bool     `json:"IsPrivate"`
	IsProvincialPriorityListing  bool     `json:"IsProvincialPriorityListing"`
	IsTopAd                      bool     `json:"IsTopAd"`
	IsTopSpotListing             bool     `json:"IsTopSpotListing"`
	IsXplListing                 bool     `json:"IsXplListing"`
	IsDigitalRetailListing       bool     `json:"IsDigitalRetailListing"`
	HasTryBeforeYouBuy           bool     `json:"HasTryBeforeYouBuy"`
	HasMoneyBackGuarantee        bool     `json:"HasMoneyBackGuarantee"`
	IsOnlineSellerPlus           bool     `json:"IsOnlineSellerPlus"`
	IsInlineListing              bool     `json:"IsInlineListing"`
	IsSwipeProListing            bool     `json:"IsSwipeProListing"`
	IsTransparencyEnabled        bool     `json:"IsTransparencyEnabled"`
	IsValidSpsPriceVisiblePlus   bool     `json:"IsValidSpsPriceVisiblePlus"`
	MsrpDealerOptOut             bool     `json:"MsrpDealerOptOut"`
	ListingType                  int      `json:"ListingType"`
	Make                         string   `json:"Make"`
	Model                        string   `json:"Model"`
	Odometer                     int      `json:"Odometer"`
	Position                     int      `json:"Position"`
	Price                        float64  `json:"Price"`
	PriceGraphType               int      `json:"PriceGraphType"`
	ProvinceAbbr                 string   `json:"ProvinceAbbr"`
	Proximity                    string   `json:"Proximity"`
	SellerCity                   string   `json:"SellerCity"`
	SellerLogoURL                string   `json:"SellerLogoUrl"`
	SellerLogoResourceLocation   int      `json:"SellerLogoResourceLocation"`
	SellerName                   string   `json:"SellerName"`
	SellerProvinceAbbr           string   `json:"SellerProvinceAbbr"`
	SimilarVehicles              struct {
		Text       string `json:"Text"`
		ViewAllURL string `json:"ViewAllUrl"`
	} `json:"SimilarVehicles,omitempty"`
	SourceID                  int           `json:"SourceId"`
	Status                    int           `json:"Status"`
	StrikeThroughPrice        float64       `json:"StrikeThroughPrice,omitempty"`
	IsCreditConnectAvailable  bool          `json:"IsCreditConnectAvailable"`
	IsFinancePrequalAvailable bool          `json:"IsFinancePrequalAvailable"`
	Title                     string        `json:"Title"`
	TitleWithTrim             string        `json:"TitleWithTrim"`
	Year                      int           `json:"Year"`
	IsNpv                     bool          `json:"IsNpv"`
	IsRvCare                  bool          `json:"IsRvCare"`
	IsVehicleSpecialist       bool          `json:"IsVehicleSpecialist"`
	HasMobialsReviews         bool          `json:"HasMobialsReviews"`
	VehicleCategory           string        `json:"VehicleCategory"`
	FieldBodyType             string        `json:"FieldBodyType"`
	GoogleRating              float64       `json:"GoogleRating"`
	GoogleMapsLinkURL         string        `json:"GoogleMapsLinkUrl"`
	DeltaPrice                string        `json:"DeltaPrice"`
	EnableSrpListingsV2       bool          `json:"EnableSrpListingsV2"`
	Olympus                   bool          `json:"Olympus"`
	ShowCityOnSrpListing      bool          `json:"ShowCityOnSrpListing"`
	WithShoppingExperience    string        `json:"WithShoppingExperience"`
	OemCertification          int           `json:"OemCertification"`
	Trim                      string        `json:"Trim"`
	ConditionList             []interface{} `json:"ConditionList"`
	FeatureList               []string      `json:"FeatureList"`
	SpecList                  []string      `json:"SpecList"`
	PostedDate                string        `json:"PostedDate"`
	DriveTrain                string        `json:"DriveTrain"`
	Transmission              string        `json:"Transmission,omitempty"`
	IsEnableIcoSrp            bool          `json:"IsEnableIcoSrp"`
	IcoVdpLink                string        `json:"IcoVdpLink"`
	ShowInsuranceWidgetOnTop  bool          `json:"ShowInsuranceWidgetOnTop"`
	SupportsImageGallery      bool          `json:"SupportsImageGallery"`
	Badges                    []struct {
		Caption      string `json:"Caption"`
		URL          string `json:"Url"`
		IsNewFeature bool   `json:"IsNewFeature"`
		GaBadgeName  string `json:"GaBadgeName"`
		QatSelector  string `json:"QatSelector"`
	} `json:"Badges"`
	ShowPriceDeltaFromiQ    bool    `json:"ShowPriceDeltaFromiQ"`
	IsAdFromAreasHeader     bool    `json:"IsAdFromAreasHeader"`
	IsAdAllListingsHeader   bool    `json:"IsAdAllListingsHeader"`
	IsTopSpotDiffXSEnabled  bool    `json:"IsTopSpotDiffXSEnabled"`
	IsTopSpotDiffDTEnabled  bool    `json:"IsTopSpotDiffDTEnabled"`
	StrikeThroughSaveAmount float64 `json:"StrikeThroughSaveAmount,omitempty"`
	IsAmvic                 bool    `json:"IsAmvic"`
	ShowBestPricedDealer    bool    `json:"ShowBestPricedDealer"`
	ShowTopSpotDiff         bool    `json:"ShowTopSpotDiff"`
	AdSortPoint             float64 `json:"AdSortPoint"`
	AdSortPointXsVar1       float64 `json:"AdSortPointXsVar1"`
	AdSortPointXsVar2       float64 `json:"AdSortPointXsVar2"`
	ShowSortPoint           bool    `json:"ShowSortPoint"`
	Vin                     string  `json:"Vin"`
	IsVirtualDealer bool `json:"IsVirtualDealer"`
	IsHybridDealer  bool `json:"IsHybridDealer"`
	IsMobile        bool `json:"IsMobile"`
	Microsite       struct {
		SiteID                         int    `json:"SiteId"`
		MicrositeType                  int    `json:"MicrositeType"`
		Culture                        string `json:"Culture"`
		LandingURLSegment              string `json:"LandingUrlSegment"`
		SearchResultsURLSegment        string `json:"SearchResultsUrlSegment"`
		DisplayText                    string `json:"DisplayText"`
		ShortName                      string `json:"ShortName"`
		ShortNameGender                string `json:"ShortNameGender"`
		RequiresType                   bool   `json:"RequiresType"`
		RequiresSubType                bool   `json:"RequiresSubType"`
		Category2Ids                   []int  `json:"Category2Ids"`
		DisableSeoModel                bool   `json:"DisableSeoModel"`
		DefaultWithPrice               bool   `json:"DefaultWithPrice"`
		DefaultWithPhotos              bool   `json:"DefaultWithPhotos"`
		IsNpv                          bool   `json:"IsNpv"`
		DisplayNeuvesInNpvPopularLinks bool   `json:"DisplayNeuvesInNpvPopularLinks"`
	} `json:"Microsite"`
	Msrp           float64 `json:"Msrp,omitempty"`
	MsrpSaveAmount float64 `json:"MsrpSaveAmount,omitempty"`
	SpinDataModel  struct {
		IsEnabled          bool      `json:"IsEnabled"`
		Provider           string    `json:"Provider"`
		SpinDataLastUpdate time.Time `json:"SpinDataLastUpdate"`
		CdnURL             string    `json:"CdnUrl"`
	} `json:"SpinDataModel,omitempty"`
	Longitude float64 `json:"Longitude"`
	Latitude  float64 `json:"Latitude"`
}